theme: minima
title: Portfolio
author: Juan Pablo Guzman Alvarez
email: jpguz0709@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
I believe that science, engineering,society, and art are dynamically interwoven following nature’s guide,led by human soul.

# social links
github_username:  JP-GuzmanAlvarez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
